# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e3465cb194b38bba8b1deb451a153ab45f3bc41fa23237f89bb9bee15d34c93d508e35dc4241e4653f3ff16f49a5e18b202763cf890e3c3d71320cdd4f55750

test:
  secret_key_base: f9152c17a97f8260e93e8fea88bfd4691559e6ea32b9b5c985d4e3bf64b1abc7faac31c7a4aaf4fd426e4739ca1e5502ff1f5091a9dfa8268132757fa39805fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
